name: SavageCore
version: 1.4-STABLE
main: net.savagellc.savagecore.SavageCore
api-version: '1.13'
authors: [Ryder]
description: A plugin to improve the Factions experience.
commands:
  savagecore:
    aliases:
      - score
    description: The base commands for SavageCore
permissions:
  savagecore.reload:
    description: Allows you to reload the plugin.
  savagecore.view:
    description: Displays a list of commands.